// AUTO-GENERATED by scripts/embed-migrations.ts — do not edit by hand.
// drizzle/*.sql をバイナリに同梱するための埋め込み表現。
import type { MigrationMeta } from "drizzle-orm/migrator";

export const embeddedMigrations: MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `repos` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`root_commit` text,\n\t`name` text NOT NULL,\n\t`first_seen_at` text NOT NULL,\n\t`last_seen_at` text NOT NULL\n);\n",
      "\nCREATE TABLE `review_entries` (\n\t`review_id` text NOT NULL,\n\t`seq` integer NOT NULL,\n\t`author` text NOT NULL,\n\t`body` text NOT NULL,\n\t`at` text NOT NULL,\n\t`agent_session` text,\n\tPRIMARY KEY(`review_id`, `seq`),\n\tFOREIGN KEY (`review_id`) REFERENCES `reviews`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE TABLE `reviews` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`repo` text NOT NULL,\n\t`target_kind` text NOT NULL,\n\t`target_value` text NOT NULL,\n\t`worktree_root` text NOT NULL,\n\t`path` text NOT NULL,\n\t`anchor` text NOT NULL,\n\t`created_at_head` text NOT NULL,\n\t`viewed_from` text NOT NULL,\n\t`viewed_to` text NOT NULL,\n\t`status` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `reviews_repo_status_idx` ON `reviews` (`repo`,`status`);",
      "\nCREATE INDEX `reviews_target_idx` ON `reviews` (`target_kind`,`target_value`);",
    ],
    folderMillis: 1788408352827,
    hash: "3105271d40d3a7c7ccc589bc6f4a05a249ae7fdbf46749d909e23ee0f6ab1f69",
    bps: true,
  },
];
