#!/usr/bin/env bun
// drizzle/*.sql + drizzle/meta/_journal.json を読み、単一バイナリに同梱できる
// src/server/db/migrations.generated.ts を生成する。
// drizzle-orm/bun-sqlite/migrator の readMigrationFiles と同じ形の
// { sql: string[]; folderMillis: number; hash: string; bps: boolean }[] を作る。

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DRIZZLE_DIR = join(import.meta.dir, "..", "drizzle");
const OUT_FILE = join(import.meta.dir, "..", "src", "server", "db", "migrations.generated.ts");

type Journal = {
  entries: { idx: number; when: number; tag: string; breakpoints: boolean }[];
};

function sha256Hex(text: string): string {
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(text);
  return hasher.digest("hex");
}

function main() {
  const journalPath = join(DRIZZLE_DIR, "meta", "_journal.json");
  const journal = JSON.parse(readFileSync(journalPath, "utf8")) as Journal;

  const migrations = journal.entries.map((entry) => {
    const sqlPath = join(DRIZZLE_DIR, `${entry.tag}.sql`);
    const raw = readFileSync(sqlPath, "utf8");
    const sql = raw.split("--> statement-breakpoint");
    const hash = sha256Hex(raw);
    return { sql, folderMillis: entry.when, hash, bps: entry.breakpoints };
  });

  const files = readdirSync(DRIZZLE_DIR).filter((f) => f.endsWith(".sql"));
  if (files.length !== migrations.length) {
    throw new Error(
      `embed-migrations: found ${files.length} .sql files but journal has ${migrations.length} entries`,
    );
  }

  const body = `// AUTO-GENERATED by scripts/embed-migrations.ts — do not edit by hand.
// drizzle/*.sql をバイナリに同梱するための埋め込み表現。
import type { MigrationMeta } from "drizzle-orm/migrator";

export const embeddedMigrations: MigrationMeta[] = ${JSON.stringify(migrations, null, 2)};
`;
  writeFileSync(OUT_FILE, body);
  console.log(`embed-migrations: wrote ${OUT_FILE} (${migrations.length} migration(s))`);
}

main();
